services:
  teamtex:
    # Use the pre-built framework image from GHCR
    image: ghcr.io/yursds/teamtex-base:latest
    volumes:
      - ..:/workspace:cached
    # Overrides default command so container stays running
    command: /bin/sh -c "while sleep 1000; do :; done"
